/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "V-Clean Enterprise",
  "tagline": "Professional USB/Drive Cleaning Utility for Windows",
  "favicon": "img/favicon.ico",
  "url": "https://laughing-loop.github.io",
  "baseUrl": "/vClean-Docs/",
  "organizationName": "laughing-loop",
  "projectName": "vClean-Docs",
  "onBrokenLinks": "warn",
  "trailingSlash": false,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/laughing-loop/vClean-Docs/tree/main/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "keywords",
        "content": "vclean, v-clean, v clean, vclean enterprise, vcleaner, v cleaner, vcleen, vkleen, vclene, USB cleaner, USB virus remover, USB malware scanner, pendrive cleaner, pendrive virus remover, pendrive shortcut virus, shortcut virus remover, shortcut virus cleaner, remove shortcut virus, pendrive shortcut virus remover, USB shortcut virus, flash drive shortcut virus, autorun virus remover, autorun.inf virus, autorun virus cleaner, recycler virus, recycler folder virus, drive cleaner, disk cleaner, temp file cleaner, temporary files remover, junk file cleaner, Windows cleaner, Windows optimizer, system cleaner, PC cleaner, computer cleaner, free cleaner, open source cleaner, portable cleaner, USB drive cleaner, external drive cleaner, flash drive cleaner, memory stick cleaner, thumb drive cleaner, malware removal tool, virus scanner, system optimization, disk cleanup, storage cleaner, cache cleaner, Windows 10 cleaner, Windows 11 cleaner, PowerShell utility, free USB cleaner, best USB cleaner, USB cleaning software, drive cleaning tool, system maintenance, PC optimization, computer maintenance, free system cleaner, lightweight cleaner, fast cleaner, safe cleaner, trusted cleaner, pen drive virus, pen drive cleaner, how to remove shortcut virus, remove virus from pendrive, clean pendrive virus, USB virus protection, USB security tool"
      },
      {
        "name": "description",
        "content": "V-Clean Enterprise - Free USB/pendrive cleaner and shortcut virus remover for Windows 10/11. Remove shortcut virus, autorun virus, temporary files, junk files, malware. Lightweight (117 KB), portable, safe. Download now!"
      },
      {
        "name": "author",
        "content": "LaughingLoop"
      },
      {
        "property": "og:title",
        "content": "V-Clean Enterprise - Free USB & Drive Cleaner for Windows"
      },
      {
        "property": "og:description",
        "content": "Professional USB and drive cleaning utility. Remove temp files, detect malware, optimize Windows 10/11. Free, open-source, portable (117 KB). Download now!"
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:url",
        "content": "https://laughing-loop.github.io/vClean-Docs/"
      },
      {
        "property": "og:image",
        "content": "https://laughing-loop.github.io/vClean-Docs/img/screenshot-main.png"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:title",
        "content": "V-Clean Enterprise - Free USB & Drive Cleaner"
      },
      {
        "name": "twitter:description",
        "content": "Free, open-source USB cleaner for Windows. Remove junk files, detect malware, optimize your PC. Only 117 KB!"
      },
      {
        "name": "twitter:image",
        "content": "https://laughing-loop.github.io/vClean-Docs/img/screenshot-main.png"
      },
      {
        "name": "robots",
        "content": "index, follow"
      },
      {
        "name": "googlebot",
        "content": "index, follow"
      },
      {
        "name": "bingbot",
        "content": "index, follow"
      },
      {
        "name": "language",
        "content": "English"
      },
      {
        "name": "revisit-after",
        "content": "7 days"
      }
    ],
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "image": "img/screenshot-main.png",
    "navbar": {
      "title": "V-Clean Enterprise",
      "logo": {
        "alt": "V-Clean Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "to": "/",
          "position": "left",
          "label": "Home",
          "activeBaseRegex": "^/$"
        },
        {
          "to": "/download",
          "position": "left",
          "label": "Download"
        },
        {
          "to": "/features",
          "position": "left",
          "label": "Features"
        },
        {
          "to": "/faq",
          "position": "left",
          "label": "FAQ"
        },
        {
          "type": "dropdown",
          "label": "Docs",
          "position": "left",
          "items": [
            {
              "label": "Quick Start",
              "to": "/quick-start"
            },
            {
              "label": "Troubleshooting",
              "to": "/troubleshooting"
            }
          ]
        },
        {
          "href": "https://github.com/laughing-loop/vClean-Utility",
          "className": "github-button",
          "position": "right",
          "label": "GitHub",
          "title": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
